# Benchmarks, analysis and inspection of the BuildingElectricity task and datasets

Given aerial imagery of a building together with meteorological conditions in the surrounding region over the preceding 24 hours, the goal of the BuildingElectricity task is to predict the building’s electrical load profile for the subsequent 24-hour forecasting horizon. 

This task addresses the challenge of short-term spatial electricity demand forecasting, where accurate predictions can substantially improve the planning and operation of distributed renewable energy resources, such as rooftop photovoltaic systems and micro-wind turbines. In addition, reliable building-level load forecasts support the optimal sizing and dispatch of energy storage systems and enable more effective coordination of flexible demand through demand response programs.

The BuildingElectricity task is multimodal and combines aerial building imagery, historical electricity consumption time series, and meteorological variables.

The BuildingElectricity task is formulated as a supervised learning problem, where models are trained to predict future building-level electricity load profiles from historical meteorological observations, aerial imagery, and a given time stamp.

The prediction target is a 24-hour electricity demand time series for an individual building, making the task a multi-step time-series forecasting problem with multimodal inputs.

We define 12 sub-task datasets grouped into two benchmark settings: one containing data from 92 buildings and another containing data from 451 buildings. Across both settings, the sub-tasks are designed to evaluate temporal, spatial, and spatio-temporal generalization capabilities, as well as the impact of incorporating historical electricity load measurements as additional input features.


## Overview
---
1. Creating benchmarks
2. Analysing characteristics
3. Inspecting aigrids data
4. Inspecting processed data
5. Inspecting raw data

In [5]:
import os
import sys
import pandas as pd

import utils
import aigrids

# set the path to your configuration file here.
path_cfg = '../config_arsam.yml'

# load the configuration file and show us
cfg = utils.parse_config(path_cfg)
cfg

{'root_path_datasets': '/hpcwork/p0027791/AI-grids',
 'list_avail_tasknames': ['OPFData',
  'PowerGraph',
  'SolarCube',
  'BuildingElectricity',
  'WindFarm']}

## 1. Creating benchmarks

In [7]:
# TODO

## 2. Analysing characteristics

In [8]:
# TODO

## 3. Inspecting aigrids data

In [2]:
taskdata = aigrids.load.load_task(
    'BuildingElectricity', 
    'odd_time_buildings92',
    cfg['path_root'],
    data_frac = 0.01
)

Processing odd_time_buildings92 for BuildingElectricity.
Using 1% of total data as specified by user.
Continuing with max_workers=1024
Continuing with max_workers_download=4
Preparing local data directory for BuildingElectricity
Error fetching file list: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/datasets/AI4Climate/BuildingElectricity/tree/main (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad1330cc40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

Found 0 files to manage (download if needed).
Data for AI4Climate/BuildingElectricity is now available at ../../donti_group_shared/AI4Climate/processed/BuildingElectricity.

Preparing subtask odd_time_buildings92
Data for odd_time_buildings92 successfully loaded.

In [ ]:
# TODO

## 4. Inspecting processed data

In [ ]:
# set path to processed data
path_processed = os.path.join(cfg['path_root'], 'processed', 'BuildingElectricity')

# csv file name
csv_filename = 'load_profiles.csv'

# path to processed data
path_profile92_buildingimage =  os.path.join(path_processed, 'profiles_92', 'building imagery', 'raw')
path_profile92_loadprofiles =  os.path.join(path_processed, 'profiles_92', 'building-year profiles', 'original')
path_profile92_clusterimage =  os.path.join(path_processed, 'profiles_92', 'cluster imagery')
path_profile92_meteodata =  os.path.join(path_processed, 'profiles_92', 'meteo data')
path_profile451_buildingimage =  os.path.join(path_processed, 'profiles_451', 'building imagery', 'raw')
path_profile451_loadprofiles =  os.path.join(path_processed, 'profiles_451')
path_profile451_clusterimage =  os.path.join(path_processed, 'profiles_451', 'cluster imagery')
path_profile451_meteodata =  os.path.join(path_processed, 'profiles_451', 'meteo data')

In [5]:
# inspect load profiles for 451 building dataset
csv_file451_path = os.path.join(path_profile451_loadprofiles, csv_filename)
df_load_profiles451 = pd.read_csv(csv_file451_path)
df_load_profiles451

,building ID,1,2,3,4,5,6,7,8,9,...,442,443,444,445,446,447,448,449,450,451
0,cluster ID,32.00,48.00,57.00,76.00,11.000,11.000,11.000,24.000,11.000,...,16.00,44.00,63.00,16.00,53.00,16.00,44.00,63.00,83.00,73.00
1,2014-01-01 00:15:00,0.24,8.64,0.43,1.14,6.346,1.423,0.185,0.379,0.346,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,2014-01-01 00:30:00,0.32,8.04,0.34,1.23,10.559,2.092,0.188,0.309,0.348,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,2014-01-01 00:45:00,0.24,7.90,0.45,1.23,10.401,0.596,0.168,0.282,0.260,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,2014-01-01 01:00:00,0.32,7.84,0.39,1.14,10.385,0.184,0.193,0.349,0.296,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35036,2014-12-31 23:00:00,0.24,9.77,1.55,1.02,0.459,2.072,0.183,0.712,0.237,...,0.88,0.15,0.28,0.01,0.88,1.84,0.55,0.14,0.01,0.12
35037,2014-12-31 23:15:00,0.24,8.31,0.52,1.05,9.001,1.490,0.318,3.562,0.324,...,0.25,0.16,0.28,0.95,0.34,1.16,0.79,0.13,0.00,0.14
35038,2014-12-31 23:30:00,0.24,8.35,0.32,0.96,10.510,0.161,0.395,3.826,0.247,...,0.06,0.14,0.24,1.19,0.61,1.00,0.73,0.11,0.01,0.12
35039,2014-12-31 23:45:00,0.32,8.24,0.27,0.96,10.598,0.195,0.193,4.045,0.278,...,0.06,0.16,0.20,1.19,0.18,0.90,0.37,0.16,0.03,0.02
35040,2015-01-01 00:00:00,0.24,8.06,0.39,1.02,10.553,0.548,0.189,3.635,0.284,...,0.06,0.19,0.26,1.20,0.21,0.87,0.81,0.09,0.01,0.01

## 5. Inspecting raw data

In [1]:
# set path to raw data
path_raw = os.path.join(cfg['path_root'], 'raw', 'BuildingElectricity')

# csv file name
csv_filename = '2014 building-year profiles.csv'

# path to raw data
path_profile92_buildingimage =  os.path.join(path_raw, 'profiles_92', 'building imagery', 'raw')
path_profile92_loadprofiles =  os.path.join(path_raw, 'profiles_92', 'building-year profiles', 'original')
path_profile92_clusterimage =  os.path.join(path_raw, 'profiles_92', 'cluster imagery')
path_profile92_meteodata =  os.path.join(path_raw, 'profiles_92', 'meteo data')
path_profile451_buildingimage =  os.path.join(path_raw, 'profiles_451', 'building imagery', 'raw')
path_profile451_loadprofiles =  os.path.join(path_raw, 'profiles_451', 'building-year profiles', 'original')
path_profile451_clusterimage =  os.path.join(path_raw, 'profiles_451', 'cluster imagery')
path_profile451_meteodata =  os.path.join(path_raw, 'profiles_451', 'meteo data')

In [2]:
# inspect load profiles for 92 building dataset
csv_file92_path = os.path.join(path_profile92_loadprofiles, csv_filename)
df_load_profiles92 = pd.read_csv(csv_file92_path)
df_load_profiles92

,building ID,1,2,3,4,5,6,7,8,9,...,83,84,85,86,87,88,89,90,91,92
0,cluster ID,2.000,2.000,3.000,3.000,3.000,5.000,4.000,5.000,5.000,...,2.000,2.000,1.000,2.000,2.000,2.000,2.000,2.000,2.000,2.000
1,year,2014.000,2014.000,2014.000,2014.000,2014.000,2014.000,2014.000,2014.000,2014.000,...,2014.000,2014.000,2014.000,2014.000,2014.000,2014.000,2014.000,2014.000,2014.000,2014.000
2,2014-01-01 00:15:00,0.379,2.836,0.097,2.466,1.183,0.675,0.342,0.022,0.121,...,0.125,0.073,0.159,0.153,0.750,2.482,1.499,1.818,0.073,3.667
3,2014-01-01 00:30:00,0.309,0.728,0.087,2.505,1.332,0.715,0.397,0.033,0.138,...,0.156,0.065,0.176,0.173,0.740,2.665,1.588,1.585,0.052,3.522
4,2014-01-01 00:45:00,0.282,0.426,0.092,2.507,0.749,0.439,0.451,0.022,0.181,...,0.122,0.075,0.344,0.140,0.714,2.577,1.540,1.552,0.068,2.889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35037,2014-12-31 23:00:00,0.721,0.999,0.060,0.304,0.027,1.920,0.453,0.305,0.031,...,0.167,0.137,0.153,0.176,0.769,0.067,0.006,0.089,0.014,0.930
35038,2014-12-31 23:15:00,3.562,2.832,0.053,0.321,1.242,1.212,0.465,0.247,0.051,...,0.172,0.077,0.161,0.160,0.801,0.077,0.005,0.063,0.015,0.714
35039,2014-12-31 23:30:00,3.826,3.126,0.066,0.298,2.647,0.193,0.496,0.244,0.020,...,0.176,0.055,0.147,0.182,0.767,0.133,0.032,0.031,0.024,0.719
35040,2014-12-31 23:45:00,4.053,2.405,0.077,0.218,2.663,0.186,0.487,0.248,0.022,...,0.189,0.077,0.065,0.192,0.779,0.076,0.006,0.004,0.012,0.823
35041,2015-01-01 00:00:00,3.639,0.322,0.076,0.197,2.334,0.203,0.470,0.238,0.060,...,0.153,0.078,0.058,0.170,0.759,0.068,0.104,0.025,0.017,1.419

In [3]:
# inspect load profiles for 451 building dataset
csv_file451_path = os.path.join(path_profile451_loadprofiles, csv_filename)
df_load_profiles451 = pd.read_csv(csv_file451_path)
df_load_profiles451

,building ID,1,2,3,4,5,6,7,8,9,...,450,451,452,453,454,455,456,457,458,459
0,cluster ID,32.00,48.00,57.00,76.00,11.000,11.000,11.000,24.000,11.000,...,16.00,44.00,63.00,16.00,53.00,16.00,44.00,63.00,83.00,73.00
1,year,2014.00,2014.00,2014.00,2014.00,2014.000,2014.000,2014.000,2014.000,2014.000,...,2014.00,2014.00,2014.00,2014.00,2014.00,2014.00,2014.00,2014.00,2014.00,2014.00
2,2014-01-01 00:15:00,0.24,8.64,0.43,1.14,6.346,1.423,0.185,0.379,0.346,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,2014-01-01 00:30:00,0.32,8.04,0.34,1.23,10.559,2.092,0.188,0.309,0.348,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,2014-01-01 00:45:00,0.24,7.90,0.45,1.23,10.401,0.596,0.168,0.282,0.260,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35037,2014-12-31 23:00:00,0.24,9.77,1.55,1.02,0.459,2.072,0.183,0.712,0.237,...,0.88,0.15,0.28,0.01,0.88,1.84,0.55,0.14,0.01,0.12
35038,2014-12-31 23:15:00,0.24,8.31,0.52,1.05,9.001,1.490,0.318,3.562,0.324,...,0.25,0.16,0.28,0.95,0.34,1.16,0.79,0.13,0.00,0.14
35039,2014-12-31 23:30:00,0.24,8.35,0.32,0.96,10.510,0.161,0.395,3.826,0.247,...,0.06,0.14,0.24,1.19,0.61,1.00,0.73,0.11,0.01,0.12
35040,2014-12-31 23:45:00,0.32,8.24,0.27,0.96,10.598,0.195,0.193,4.045,0.278,...,0.06,0.16,0.20,1.19,0.18,0.90,0.37,0.16,0.03,0.02
35041,2015-01-01 00:00:00,0.24,8.06,0.39,1.02,10.553,0.548,0.189,3.635,0.284,...,0.06,0.19,0.26,1.20,0.21,0.87,0.81,0.09,0.01,0.01

In [3]:
# inspect sample meteo file for 451 building dataset
sample_meteo_filename = 'meteo_1_2014.csv'
csv_file451_meteo = os.path.join(path_profile451_meteodata, sample_meteo_filename)
df_meteo = pd.read_csv(csv_file451_meteo)
df_meteo

,air_density,cloud_cover,local_time,precipitation,radiation_surface,radiation_toa,snow_mass,snowfall,temperature,wind_speed
0,1.153,0.824,2014-01-01 01:00:00,0.000,0.0,0.0,23.151,0.0,-4.794,3.578
1,1.153,0.824,2014-01-01 01:15:00,0.000,0.0,0.0,23.151,0.0,-4.794,3.578
2,1.153,0.824,2014-01-01 01:30:00,0.000,0.0,0.0,23.151,0.0,-4.794,3.578
3,1.153,0.824,2014-01-01 01:45:00,0.000,0.0,0.0,23.151,0.0,-4.794,3.578
4,1.152,0.921,2014-01-01 02:00:00,0.008,0.0,0.0,23.153,0.0,-4.478,3.551
...,...,...,...,...,...,...,...,...,...,...
35035,1.198,0.033,2014-12-31 23:45:00,0.000,0.0,0.0,36.560,0.0,-10.617,3.495
35036,1.198,0.042,2015-01-01 00:00:00,0.000,0.0,0.0,36.567,0.0,-10.402,3.437
35037,1.198,0.042,2015-01-01 00:15:00,0.000,0.0,0.0,36.567,0.0,-10.402,3.437
35038,1.198,0.042,2015-01-01 00:30:00,0.000,0.0,0.0,36.567,0.0,-10.402,3.437
35039,1.198,0.042,2015-01-01 00:45:00,0.000,0.0,0.0,36.567,0.0,-10.402,3.437

In [10]:
df_load_profiles451.columns

Index(['building ID', '1', '2', '3', '4', '5', '6', '7', '8', '9',
       ...
       '450', '451', '452', '453', '454', '455', '456', '457', '458', '459'],
      dtype='object', length=452)

In [9]:
df_load_profiles451.columns[1:]

Index(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
       ...
       '450', '451', '452', '453', '454', '455', '456', '457', '458', '459'],
      dtype='object', length=451)