# Benchmarks, analysis and inspection of the WindFarm task and datasets

Given two weeks of historical power generation measurements for each turbine in a wind farm, together with the relative geographic positions of the turbines, the goal of the WindFarm task is to predict the active power output profile of the wind farm over the subsequent 48-hour forecasting horizon.

Accurate forecasting of wind farm power generation enables power system operators to better manage the inherent variability and uncertainty of wind energy production. Improved forecasts support the efficient utilization of energy storage systems and flexible demand resources, enhance the planning and dispatch of transmission networks, and ultimately facilitate the reliable integration of larger shares of wind energy into existing power grids.

The WindFarm task is based on multivariate spatio-temporal time-series data, consisting of historical turbine-level power generation measurements together with the relative geographic positions of turbines within the wind farm.

The WindFarm task is formulated as a supervised learning problem, where models are trained to predict future wind power generation profiles from historical turbine-level measurements and spatial information describing turbine locations within the wind farm. The task corresponds to a multi-step spatio-temporal forecasting problem, in which models must learn both temporal dependencies in wind power generation and spatial interactions among turbines induced by wind flow dynamics.

We define six forecasting sub-task datasets grouped according to two prediction horizons: forecasting wind power generation 48 hours ahead and forecasting wind power generation 72 hours ahead. Within each prediction horizon, the sub-tasks are designed to evaluate temporal, spatial, and spatio-temporal generalization capabilities of forecasting models.


## Overview
---
1. Creating benchmarks
2. Analysing characteristics
3. Inspecting aigrids data
4. Inspecting processed data
5. Inspecting raw data

In [1]:
import os
import sys

import pandas as pd
from IPython.display import display

import utils
import aigrids

# set the path to your configuration file here.
path_cfg = '../config_arsam.yml'

# load the configuration file and show us
cfg = utils.parse_config(path_cfg)
cfg

## 1. Creating benchmarks

In [ ]:
# TODO

## 2. Analysing characteristics

In [ ]:
# TODO

## 3. Inspecting aigrids data

In [2]:
taskdata = load.load_task(
    'WindFarm', 
    'odd_time_predict48h',
    path_root,
    data_frac = 0.01
)

Processing odd_time_predict48h for WindFarm.
Using 1% of total data as specified by user.
Continuing with max_workers=1024
Continuing with max_workers_download=4
Preparing local data directory for WindFarm
Error fetching file list: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/datasets/AI4Climate/WindFarm/tree/main (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0c383b0f70>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

Found 0 files to manage (download if needed).
Data for AI4Climate/WindFarm is now available at ../../donti_group_shared/AI4Climate/processed/WindFarm.

Preparing subtask odd_time_predict48h

ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

In [ ]:
taskdata

## 4. Inspecting processed data

In [ ]:
# SKIP

## 5. Inspecting raw data

In [4]:
# set paths to data files
path_raw_data_root = os.path.join(cfg['path_root', 'raw', 'WindFarm'])
path_sdwpf_full = os.path.join(path_raw_data_root, 'sdwpf_full')
path_sdwpf_kddcup = os.path.join(path_raw_data_root, 'sdwpf_kddcup')

path_full_scada = os.path.join(path_sdwpf_full, 'sdwpf_2001_2112_full.csv')
path_full_location = os.path.join(path_sdwpf_full, 'sdwpf_turb_location_elevation.csv')
path_kddcup_scada = os.path.join(path_sdwpf_kddcup, 'sdwpf_245days_v1.csv')
path_kddcup_location = os.path.join(path_sdwpf_kddcup, 'sdwpf_baidukddcup2022_turb_location.csv')

In [5]:
scada_data = pd.read_csv(path_full_scada)
location_data = pd.read_csv(path_full_location)

display(scada_data)
display(location_data)

,TurbID,Tmstamp,Wspd,Wdir,Etmp,Itmp,Ndir,Pab1,Pab2,Pab3,Prtv,T2m,Sp,RelH,Wspd_w,Wdir_w,Tp,Patv
0,57,2020-01-03 04:25:00,7.935,0.055,2.185,23.415,236.59,-0.840,-0.840,-0.845,29.680,-12.312683,85893.516,0.529154,5.191925,52.389540,0.0,976.925
1,57,2020-01-03 04:55:00,6.425,-1.860,2.945,23.550,236.59,-0.610,-0.605,-0.610,14.480,-12.312683,85893.516,0.529154,5.191925,52.389540,0.0,610.830
2,57,2020-01-03 05:25:00,5.945,-1.635,3.720,23.350,236.59,-0.435,-0.435,-0.435,15.270,-11.709015,85836.430,0.516070,5.563238,56.420248,0.0,483.850
3,57,2020-01-03 05:55:00,6.290,1.220,4.385,23.285,236.59,-0.510,-0.510,-0.510,19.030,-11.709015,85836.430,0.516070,5.563238,56.420248,0.0,536.970
4,57,2020-01-03 06:25:00,5.650,3.790,4.945,23.265,243.84,-0.355,-0.355,-0.355,9.795,-10.475830,85820.766,0.515158,6.000677,55.780818,0.0,431.700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11361185,123,2021-12-31 23:30:00,2.330,54.980,-0.020,5.320,-154.93,90.390,90.350,90.040,-0.300,-12.468079,86241.920,0.577978,2.974639,359.635260,0.0,-0.300
11361186,123,2021-12-31 23:40:00,2.420,13.460,0.090,5.170,-105.64,86.180,86.140,86.070,-0.300,-12.468079,86241.920,0.577978,2.974639,359.635260,0.0,-0.300
11361187,123,2021-12-31 23:50:00,2.290,20.250,0.300,5.540,-96.39,90.230,90.140,90.390,-0.300,-12.468079,86241.920,0.577978,2.974639,359.635260,0.0,-0.300
11361188,123,2022-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.099030,86257.430,0.613977,3.329529,24.708881,0.0,NaN
11361189,123,2022-01-01 00:10:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.099030,86257.430,0.613977,3.329529,24.708881,0.0,NaN

     TurbID          x           y          Ele
0         1  3349.8515  5939.23193  1430.700073
1         2  3351.0017  6416.64673  1434.200073
2         3  3314.7797  6892.18395  1436.900024
3         4  3352.0940  7366.14203  1439.700073
4         5  3355.3420  7841.20175  1441.700073
..      ...        ...         ...          ...
129     130    12.6509  4814.60040  1412.400024
130     131    23.3458  5284.65439  1416.300049
131     132    62.6774  5749.90633  1421.000000
132     133    78.4309  6231.32903  1423.400024
133     134    11.3385  6713.46517  1424.700073

[134 rows x 4 columns]

In [21]:
scada_data_kddcup = pd.read_csv(path_kddcup_scada)
location_data_kddcup = pd.read_csv(path_kddcup_location)

display(scada_data_kddcup)
display(location_data_kddcup)

,TurbID,Day,Tmstamp,Wspd,Wdir,Etmp,Itmp,Ndir,Pab1,Pab2,Pab3,Prtv,Patv
0,1,1,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,00:10,6.17,-3.99,30.73,41.80,25.92,1.00,1.00,1.00,-0.25,494.66
2,1,1,00:20,6.27,-2.18,30.60,41.63,20.91,1.00,1.00,1.00,-0.24,509.76
3,1,1,00:30,6.42,-0.73,30.52,41.52,20.91,1.00,1.00,1.00,-0.26,542.53
4,1,1,00:40,6.25,0.89,30.49,41.38,20.91,1.00,1.00,1.00,-0.23,509.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4727515,134,245,23:10,7.79,2.80,-0.07,3.95,216.51,6.03,6.03,6.03,-111.69,601.44
4727516,134,245,23:20,8.06,4.39,0.23,3.94,216.51,5.81,5.81,5.81,-72.67,673.79
4727517,134,245,23:30,8.08,2.28,-0.16,4.15,216.51,0.68,0.68,0.68,-118.70,999.36
4727518,134,245,23:40,8.46,0.80,-0.14,4.32,216.51,0.02,0.02,0.02,-58.12,1100.89
4727519,134,245,23:50,8.68,0.52,-0.06,4.39,216.51,0.01,0.01,0.01,-44.75,1181.49

     TurbID          x           y
0         1  3349.8515  5939.23193
1         2  3351.0017  6416.64673
2         3  3314.7797  6892.18395
3         4  3352.0940  7366.14203
4         5  3355.3420  7841.20175
..      ...        ...         ...
129     130    12.6509  4814.60040
130     131    23.3458  5284.65439
131     132    62.6774  5749.90633
132     133    78.4309  6231.32903
133     134    11.3385  6713.46517

[134 rows x 3 columns]

In [6]:
scada_data.merge(location_data)

,TurbID,Tmstamp,Wspd,Wdir,Etmp,Itmp,Ndir,Pab1,Pab2,Pab3,...,T2m,Sp,RelH,Wspd_w,Wdir_w,Tp,Patv,x,y,Ele
0,57,2020-01-03 04:25:00,7.935,0.055,2.185,23.415,236.59,-0.840,-0.840,-0.845,...,-12.312683,85893.516,0.529154,5.191925,52.389540,0.0,976.925,5360.5356,11165.39719,1465.500000
1,57,2020-01-03 04:55:00,6.425,-1.860,2.945,23.550,236.59,-0.610,-0.605,-0.610,...,-12.312683,85893.516,0.529154,5.191925,52.389540,0.0,610.830,5360.5356,11165.39719,1465.500000
2,57,2020-01-03 05:25:00,5.945,-1.635,3.720,23.350,236.59,-0.435,-0.435,-0.435,...,-11.709015,85836.430,0.516070,5.563238,56.420248,0.0,483.850,5360.5356,11165.39719,1465.500000
3,57,2020-01-03 05:55:00,6.290,1.220,4.385,23.285,236.59,-0.510,-0.510,-0.510,...,-11.709015,85836.430,0.516070,5.563238,56.420248,0.0,536.970,5360.5356,11165.39719,1465.500000
4,57,2020-01-03 06:25:00,5.650,3.790,4.945,23.265,243.84,-0.355,-0.355,-0.355,...,-10.475830,85820.766,0.515158,6.000677,55.780818,0.0,431.700,5360.5356,11165.39719,1465.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11361185,123,2021-12-31 23:30:00,2.330,54.980,-0.020,5.320,-154.93,90.390,90.350,90.040,...,-12.468079,86241.920,0.577978,2.974639,359.635260,0.0,-0.300,61.3350,11944.36985,1461.700073
11361186,123,2021-12-31 23:40:00,2.420,13.460,0.090,5.170,-105.64,86.180,86.140,86.070,...,-12.468079,86241.920,0.577978,2.974639,359.635260,0.0,-0.300,61.3350,11944.36985,1461.700073
11361187,123,2021-12-31 23:50:00,2.290,20.250,0.300,5.540,-96.39,90.230,90.140,90.390,...,-12.468079,86241.920,0.577978,2.974639,359.635260,0.0,-0.300,61.3350,11944.36985,1461.700073
11361188,123,2022-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-13.099030,86257.430,0.613977,3.329529,24.708881,0.0,NaN,61.3350,11944.36985,1461.700073
11361189,123,2022-01-01 00:10:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-13.099030,86257.430,0.613977,3.329529,24.708881,0.0,NaN,61.3350,11944.36985,1461.700073